# train dataset dir
traindir: ../../train2

#test dataset dir
testdir: ../../test2

#learning rate
lr: 0.0002
epochs: 50
# model save path
save_path: ../noisy_3755.pth

num_classes: 3755

batch_size: 128
# num workers
nw: 2

best_acc: 0.0
